app = "luna-telegram-bot"

[env]
  TELEGRAM_TOKEN = "your_telegram_token"
  OWNER_CHAT_ID = "your_user_id"
  FLY_APP_NAME = "luna-telegram-bot"

[[services]]
  internal_port = 10000
  protocol = "tcp"

  [[services.ports]]
    port = 80
