name: Telegram Bot Cron Runner

on:
  schedule:
    - cron: '*/10 * * * *'   # Runs every 10 minutes
  workflow_dispatch:         # Allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
